### ISSUE TITLE
[ARCHETYPE-674] Generating a partial archetype has an API incompatibility with Maven 4

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#883]
**[Giovanni van der Schelde](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=giovds)** opened **[ARCHETYPE-674](https://issues.apache.org/jira/browse/ARCHETYPE-674?redirect=false)** and commented

With Maven 4, when you install a partial archetype and want to run mvn archetype:generate on an existing project the generation fails with the following error:

```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project demo: Execution default-cli of goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate: java.lang.NoSuchMethodError: 'java.lang.Object org.apache.maven.model.Plugin.getGoals()' 
```

It also completely removes the content of the pom.xml of the existing project.

---

**Affects:** 3.2.1

**Attachments:**
- [demo-issue.zip](https://issues.apache.org/jira/secure/attachment/13071237/demo-issue.zip) (_27.76 kB_)

**Remote Links:**
- [GitHub Pull Request #270
](https://github.com/apache/maven-archetype/pull/270)

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

The cause is

https://github.com/apache/maven-archetype/blob/master/archetype-common/src/main/java/org/apache/maven/archetype/common/MavenJDOMWriter.java

There are used reflections for model build ....

**Comment by jira-importer** [comment]
**[Yu Yu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER308103)** commented

Should we consider the compatibility mode of archetype with Maven 4.0? After updating the dependency of maven to 4.0.0-rc-1, I noticed many similar issues.
